version: '3.8'

services:
  server:
    image: vampzzz/director-dashboard-server:v1
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    restart: always

  client:
    image: vampzzz/director-dashboard-client:v1
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - server
