apiVersion: v1
kind: Service
metadata:
  name: company-client
spec:
  selector:
    app: company-client
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: NodePort