apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: director-dashboard
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/isayakmondal/director-dashboard.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true